FROM python:3.7

WORKDIR /MovieRecommendationAPI

RUN pip install pandas scikit-learn flask gunicorn

ADD ./Data ./Data
ADD MovieLens_reco_content.py MovieLens_reco_content.py
ADD FlaskAPI.py FlaskAPI.py

EXPOSE 5000

CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "main:app" ]